version: "3.8"

services:
  dual-server:
    build: .
    ports:
      - "9000:9000" # gRPC
      - "8080:8080" # HTTP
    environment:
      - GRPC_PORT=9000
      - HTTP_PORT=8080
    restart: unless-stopped
